stages:
  - pre
  - build
  - deploy

variables:
  NODE_VERSION: "18.18.0" # Node.js 版本
  DIST_DIR: "dist"       # 构建输出目录
  DEPLOY_PATH: "/var/www/norman.log.monitor.web" # 部署目标路径

# 使用带有 docker 和 localhost 标签的 Runner
default:
  tags:
    - docker
    - localhost

# Pre阶段: 环境准备工作
pre:
  stage: pre
  image: node:${NODE_VERSION}
  script:
    - echo "检查docker安装情况"
    - docker --version
    #如果没有,自动安装
    - if [ $? -ne 0 ]; then
        echo "docker未安装,开始安装docker...";
        curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun;
        echo "docker安装完成";
      fi
    - echo "检查docker有没有node镜像"
    #如果没有,自动拉取
    - docker images | grep node
    - if [ $? -ne 0 ]; then
        echo "node镜像不存在,开始拉取node镜像...";
        docker pull node:${NODE_VERSION};
        echo "node镜像拉取完成";
      fi
    #检查docker-compose有没有安装
    - echo "检查docker-compose安装情况"
    - docker-compose --version
    - if [ $? -ne 0 ]; then
        echo "docker-compose未安装,开始安装docker-compose...";
        curl -L https://get.daocloud.io/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose;
        chmod +x /usr/local/bin/docker-compose;
        echo "docker-compose安装完成";
      fi
# Build阶段: 项目依赖安装并构建
build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - >
      echo "开始 Build 阶段: 安装依赖并构建项目..." &&
      npm install &&
      npm run build &&
      echo "Build 阶段完成: 构建产物已生成"
  artifacts:
    paths:
      - ${DIST_DIR} # 保存构建的产物以便传递到后续阶段

# Deploy阶段: 部署构建的文件
deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - >
      echo "开始 Deploy 阶段: 部署到主机 ${DEPLOY_PATH}..." &&
      ls ${DIST_DIR} && cp -r ${DIST_DIR}/* ${DEPLOY_PATH} &&
      echo "Deploy 阶段完成: 文件已部署到 ${DEPLOY_PATH}"
